# Generated by Django 4.1.4 on 2023-04-12 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompulsorySaving',
            fields=[
                ('account_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('balance', models.FloatField(default=0.0)),
                ('is_suspended', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='SavingAccount',
            fields=[
                ('account_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('balance', models.FloatField(default=0.0)),
                ('is_suspended', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='SavingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('balance', models.FloatField(default=0.0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingVaultTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
                ('withdraw', models.FloatField(default=0.0)),
                ('deposit', models.FloatField(default=0.0)),
                ('interest', models.FloatField(default=0.0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.savingvault')),
            ],
        ),
        migrations.CreateModel(
            name='SavingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
                ('withdraw', models.FloatField(default=0.0)),
                ('deposit', models.FloatField(default=0.0)),
                ('interest', models.FloatField(default=0.0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.savingaccount')),
            ],
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='saving_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.savingtype'),
        ),
        migrations.CreateModel(
            name='CompulsoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
                ('withdraw', models.FloatField(default=0.0)),
                ('deposit', models.FloatField(default=0.0)),
                ('interest', models.FloatField(default=0.0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.compulsorysaving')),
            ],
        ),
    ]
