# Generated by Django 4.1.4 on 2023-04-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=225)),
                ('father_name', models.CharField(max_length=225)),
                ('garnd_father_name', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=225)),
                ('sub_city', models.CharField(max_length=225)),
                ('woreda', models.CharField(max_length=225)),
                ('house_num', models.IntegerField(default=0)),
                ('save_count', models.IntegerField(default=0)),
                ('has_saved', models.BooleanField(default=False)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone_num', models.IntegerField()),
                ('age', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
